### PR TITLE
Allow to run on rails 7

### LINKED ISSUE #113: Add support for Rails 7
trestle-active_storage was resolved to 2.0.0, which depends on
      rails (< 6, >= 5.2.0.beta2)

### PR DESCRIPTION
**Pull request by alxekb**
Updated .gemspec 

Allow it to run under rails `5.2 =< {rails version} < 8`

Closes #113

### CODE REVIEW

**Comment by alxekb** [comment]
@richardvenneman please check it out. Feel free to ask if you have any questions.

**Comment by janpawellek** [comment]
Great thank you @alxekb 👍🏻 
It would be fantastic if you could add that for Rails 7 support @richardvenneman. Thank you very much for your effort!

**Comment by richardvenneman** [comment]
Thanks for this, sorry for the wait!

**Comment by janpawellek** [comment]
Hi @richardvenneman 
Great, thank you very much! I am very happy that Rails 7 support is now available.
Could you please also release a new version of the Gem? Thank you 😃

**Pull request merged**
