### PR TITLE
Support for active storage preview

### LINKED ISSUE #1: Can I have a preview of image being uploaded as attachment?
As title says. Much appreciate if your gem supports this feature.

### PR DESCRIPTION
**Pull request by tachyons**
Fixes #1

### CODE REVIEW

**Comment by richardvenneman** [comment]
@tachyons thanks for the PR, it is nice that the previewer can resize the image. Let me test this.

But please note this doesn't fix #1 ("show image preview right after image is selected from local.")

**Comment by tachyons** [comment]
Okay, I missed that. But since preview is to be generated using backend tool, previewing right after uploading  won't be easy

**Comment by richardvenneman** [comment]
Also, in the case of an image this code is not reached. I am wondering if this code can just replace the conditional?

**Comment by tachyons** [comment]
I tried it, But got following error
`ActiveStorage::UnpreviewableError: ActiveStorage::UnpreviewableError`

**Comment by richardvenneman** [comment]
I see. It appears that `previewable?` only works with PDF and video files. For images we need `#variable?`. Let me do some more testing tonight before I merge your PR.

**Pull request closed without merging**
